hosts: [
  { host_ip: "192.168.87.87", host_name: "nexus-server"} 
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" }
  ]
